export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_END = 'REGISTER_USER_END'
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
export const STOP_SPINNER = 'STOP_SPINNER'
export const START_SPINNER = 'START_SPINNER'
export const SETUP_USER = 'SETUP_USER'

export const USER_SETUP_START = 'USER_SETUP_START'
export const USER_SETUP_SUCCESS = 'USER_SETUP_SUCCESS'
export const USER_SETUP_ERROR = 'USER_SETUP_ERROR'

export const GET_TRENDS_START = 'GET_TRENDS_START'
export const GET_TRENDS_SUCCESS = 'GET_TRENDS_SUCCESS'
export const GET_TRENDS_ERROR = 'GET_TRENDS_ERROR'

export const GET_HOMEPAGE_TWEETS_START = 'GET_HOMEPAGE_TWEETS_START'
export const GET_HOMEPAGE_TWEETS_SUCCESS = 'GET_HOMEPAGE_TWEETS_SUCCESS'
export const GET_HOMEPAGE_TWEETS_ERROR = 'GET_HOMEPAGE_TWEETS_ERROR'

export const GET_USER_PROFILE_START = 'GET_USER_PROFILE_START'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const TWEET_MAX_LENGTH = 100
export const SERVER_BASE_URL = 'http://localhost:3000'
export const CLIENT_BASE_URL = 'http://localhost:5000'
